version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - PORT=3000

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_REACT_API_BACKEND_URL=http://localhost:3000
    depends_on:
      - backend
